---
title: "0_preprocess_th184"
author: "tsuyoshi"
output: 
  html_document:
    toc: true
    toc_float: true
    df_print: paged
    code_folding: "hide"
    pandoc_args: [ 
      "--output=0_preprocess_th184.html" 
    ]
date: "`r format(Sys.time(), '%d %B, %Y')`"

---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(imcRtools)
library(zellkonverter)
library(SingleCellExperiment)
library(cytomapper)

library(ggplot2)
```

```{r specify_paths}
# Specify input paths
steinbock.paths <- c("/Users/tsuyoshi/Documents/prj_CISI/IMC_experiments/TH182_ApeendixW",
                     "/Users/tsuyoshi/Documents/prj_CISI/IMC_experiments/TH182_BreastTW1",
                     "/Users/tsuyoshi/Documents/prj_CISI/IMC_experiments/TH182_BreastTW2",
                     "/Users/tsuyoshi/Documents/prj_CISI/IMC_experiments/TH182_tissueMA2",
                     "/Users/tsuyoshi/Documents/prj_CISI/IMC_experiments/TH182_TonsilW")
meta.paths <- paste0(steinbock.paths, "/images.csv")


# Specify output path
out.path <- "/Users/tsuyoshi/Documents/prj_CISI/CISI_Data/0_tissues_th182"
# Create output directory if id doesn't exist
if (!dir.exists(out.path)) {dir.create(out.path, recursive=TRUE)}
```

```{r read_input_data}
sces <- lapply(steinbock.paths, function(x){read_steinbock(x, graphs_folder=NULL,regionprops_folder=NULL)} ) 
sces

metas <- lapply(meta.paths, function(x){read_csv(x, show_col_types = FALSE)} ) 
metas

```
```{r combine_sces}
sce <- do.call("cbind",sces)
meta <- do.call("rbind",metas)
```


```{r add_tissue_annotation}
sce$slide <- meta$recovery_file[match(paste0(sce$sample_id,".tiff"), meta$image)] %>% str_split('_') %>% lapply('[[', 4) %>% unlist()
sce$tissue <- meta$recovery_file[match(paste0(sce$sample_id,".tiff"), meta$image)] %>% str_split('_') %>% lapply('[[', 5) %>% unlist()
sce$ROI_per_tissue <- meta$recovery_file[match(paste0(sce$sample_id,".tiff"), meta$image)] %>% str_split('_') %>% lapply('[[', 6) %>% unlist()
unique(sce$slide)
unique(sce$tissue)
unique(sce$ROI_per_tissue)
```
```{r subset_genes_tissues}
sce <- sce[!rownames(sce)%in%c("HistoneH3","191Ir","193Ir"),!sce$tissue %in% c("Spleen","Kidney")]
```


```{r save_sce_as_anndata}
writeH5AD(SingleCellExperiment(list(counts=assay(sce, "counts")),
                                 colData=colData(sce),
                                 rowData=rowData(sce)), file=file.path(out.path, "sce.h5ad"))
```





