---
title: "3_A_maxcomposition"
author: "tsuyoshi"
output: 
  html_document:
    toc: true
    toc_float: true
    df_print: paged
    code_folding: "hide"
    pandoc_args: [ 
      "--output=3_A_maxcomposition.html" 
    ]
date: "`r format(Sys.time(), '%d %B, %Y')`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```

```{r library}
library(ggplot2)
library(dplyr)
library(tidyr)
```

### set up

```{r specify_paths}
# specify paths
input_path <- "/mnt/projects/data/publication/3_A_maxcomposition"
```

#### Read summary table
```{r read_df}
fn <- file.path(input_path,"result_A.csv")
df <- read.csv(fn, header = T)
df$maxcomposition <- as.factor(df$maxcomposition)
df
```

#### plot results
```{r, results="asis",fig.height = 5, fig.width = 10, fig.align = "center"}

ggplot(df, aes(x = A_L0_sum , y = Gene_average, group = A_L0_sum, color =  maxcomposition)) + 
  geom_violin() +
  xlab("Sum of non-zero entries in A (counts)") + theme_bw() +
  geom_boxplot(data = df, aes(x = A_L0_sum , y = Gene_average ), outlier.shape = NA, width= 0.1) 

ggplot(df, aes(x = A_L0_sum , y = Gene_minimum, group = A_L0_sum, color =  maxcomposition)) + 
  geom_violin() +
  xlab("Sum of non-zero entries in A (counts)") + theme_bw() +
  geom_boxplot(data = df, aes(x = A_L0_sum , y = Gene_minimum ), outlier.shape = NA, width= 0.1) 

```


