---
title: "5_X_Abtitration"
author: "tsuyoshi"
output: 
  html_document:
    toc: true
    toc_float: true
    df_print: paged
    code_folding: "hide"
    pandoc_args: [ 
      "--output=5_X_Abtitration.html" 
    ]
date: "`r format(Sys.time(), '%d %B, %Y')`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```

```{r library}
library(ggplot2)
library(cowplot)
library(dplyr)
library(tidyr)


```


### set up

```{r specify_paths}
#### specify paths
# Set general input paths to all analysis files
input_paths <- c("/mnt/projects/data/publication/4_X_normalization",
                 "/mnt/projects/data/publication/5_X_Abtitration")

```

#### Read summary table
```{r read_df}
DF <- lapply(input_paths, function(input_path){
  fn <- file.path(input_path,"result_U.csv")
  df_U <- read.csv(fn, header = T)
  fn <- file.path(input_path,"result_A.csv")
  df_A <- read.csv(fn, header = T)
  # remove X to avoid duplicated col when combined
  if (!is.null(df_A[["X"]])) df_A <- dplyr::select(df_A,-X)
  
  # add U_cond for plotting
  df_U$U_cond <- paste(df_U$methodW, df_U$ldaU, df_U$ldaW,df_U$k,df_U$num_blocks_W, sep = "_")
  
  # make condition cols into factor 
  col_names <- c("methodW","ldaU","num_blocks_W","ldaW","k","expid")
  df_U[,col_names] <- lapply(df_U[,col_names] , factor)
  
  # combine df_U to df_A
  df <- match(df_A$U_id,df_U$expid ) %>% df_U[.,] %>% data.frame(df_A) 
  
  df
})

# add Xnorm_weight for titrated data
DF[[2]]$Xnorm_weight <- "0_titrated"

# add simulated or titrated
DF[[1]]$titration <- "simulated"
DF[[2]]$titration <- "actual_Abtitration"

df <- rbind(DF[[1]],DF[[2]])
```

#### Actual titraion vs Simulated {.tabset}
```{r plot, results="asis",fig.height = 4, fig.width = 8, fig.align = "center"}
#plot actual and simulated titration
for (U_cond in unique(df$U_cond)){
  cat("##### ", U_cond, "\n")
  p <- df[df$U_cond == U_cond,] %>% 
    ggplot(aes(x=reorder(Xnorm_weight, Gene_average), y=Gene_average, color = titration)) +
    geom_violin()+ theme_bw() + ylim(0,1)+ xlab("X_Normalizaiton weight") +
    theme(axis.text.x = element_text(angle = 45, hjust = 1))
  q <- df[df$U_cond == U_cond,] %>% 
    ggplot(aes(x=reorder(Xnorm_weight, Gene_minimum), y=Gene_minimum, color = titration)) +
    geom_violin()+ theme_bw() + ylim(-0.2,1)+xlab("X_Normalizaiton weight") +
    theme(axis.text.x = element_text(angle = 45, hjust = 1))
  r <- plot_grid(p,q)
  print(r)
  cat ("\n\n")
}
```

