---
title: "7_Finalize_U"
author: "tsuyoshi"
output: 
  html_document:
    toc: true
    toc_float: true
    df_print: paged
    code_folding: "hide"
    pandoc_args: [ 
      "--output=7_Finalize_U.html" 
    ]
date: "`r format(Sys.time(), '%d %B, %Y')`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```

```{r library}
library(ComplexHeatmap)
library(circlize)

```


#### read final U
```{r}
U_final_path <- file.path("/mnt/projects/data/publication/7_Finalize_U/U/U_final.csv")
U_final <- read.csv(U_final_path,row.names = '', check.names = F )
```

#### define plotting function
```{r define_plot_U}
# input U (p x d) is DF with rownames of proteins
plot_U <- function(U){
  h <- Heatmap(U, 
               col = colorRamp2(c(0, 0.5, 1), c("navy", "white", "firebrick2")),
               column_title = paste("d =", ncol(U)),
               show_heatmap_legend = T, 
               show_column_names = FALSE, 
               show_row_dend=F, 
               show_column_dend=F, 
               row_names_gp = gpar(fontsize=8),
               column_title_gp = gpar(fontsize = 10),
               heatmap_legend_param = list(title = "module", direction = "vertical" ) #if want to show legend #"horizontal"
               )
  return(h)
  }
```

#### plot final U
```{r, results="asis", fig.height = 3, fig.width = 5, fig.align = "center"}
plot_U(U_final)
```

