---
title: "8_Finalize_A"
author: "tsuyoshi"
output: 
  html_document:
    toc: true
    toc_float: true
    df_print: paged
    code_folding: "hide"
    pandoc_args: [ 
      "--output=8_Finalize_A.html" 
    ]
date: "`r format(Sys.time(), '%d %B, %Y')`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```

```{r library}
library(ggplot2)
library(ComplexHeatmap)
library(circlize)
library(common)
library(cowplot)
library(dplyr)
library(stringr)
```


### set up

```{r specify_paths}
input_path <- "/mnt/projects/data/7_Finalize_A_16_to_8"
```


#### read A
```{r}
A_path <- file.path(input_path,"A")
best_phi_path <- file.find(A_path, "best_phi_id_*.csv")
best_phi <- read.csv(best_phi_path, row.names = 'X')
best_phi <- best_phi[c(2,5,3,8,6,7,4,1),] # reorder to match actual cisi channel order
rownames(best_phi) <- 0:7
```


```{r, results="asis",fig.height = 4, fig.width = 6, fig.align = "center"}
Heatmap(best_phi, 
        col = colorRamp2(c(0, 0.2, 1), c("navy", "white", "firebrick2")),
        heatmap_legend_param = list(title = "A", direction = "vertical"))
```




### Read tables for 7,8,9 ch comparison
```{r specify_paths2}
input_paths <- c("/mnt/projects/data/publication/8_Finalize_A_16_to_7/R2_result_A.csv",
                 "/mnt/projects/data/publication/8_Finalize_A_16_to_8/R2_result_A.csv",
                 "/mnt/projects/data/publication/8_Finalize_A_16_to_9/R2_result_A.csv")
```

#### Read summary table
```{r read_df2}
df2 <- lapply(input_paths, function(ip) {
  read.csv(ip, header = T) %>% 
    mutate(channel_no = str_split_1(str_split_1(ip,'/')[length(str_split_1(ip,'/'))-1],'_')[6] )
  }) %>% do.call("rbind",.)
```



```{r, results="asis",fig.height = 3, fig.width = 8, fig.align = "center"}

p1 <- ggplot(df2, aes(x = channel_no, y = Gene_minimum)) + geom_violin(fill = 'gray') + 
  xlab("No. of composite channels") + theme_bw() + 
  geom_boxplot(data = df2, aes(x = channel_no, y = Gene_minimum), 
               outlier.shape = NA, width= 0.1)
p2 <- ggplot(df2, aes(x = channel_no, y = Gene_average)) + geom_violin(fill = 'gray') + 
  xlab("No. of composite channels") + theme_bw() + 
  geom_boxplot(data = df2, aes(x = channel_no, y = Gene_average), 
               outlier.shape = NA, width= 0.1)

plot_grid(p1,p2)
```






